name: etoda_nagcarlan
description: "This project is a Fare Matrix Calculator and Digital TODA system for Nagcarlan."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # --- eTODA ESSENTIALS ---
  # For professional Nagcarlan branding fonts
  google_fonts: ^8.0.2

  # For Passenger side: Scanning Driver QR codes
  mobile_scanner: ^7.2.0

  # For Driver side: Generating their unique ID QR code
  qr_flutter: ^4.1.0

  # For Fair Treatment: Real-time location for digital queue & wayback trips
  geolocator: ^14.0.2

  # For managing user roles (Passenger/Driver) and Trip status
  provider: ^6.1.2

  # For simple local data storage (saving trip history on device)
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # If you have a Nagcarlan or TODA Logo, uncomment this section:
  # assets:
  #   - assets/logo.png